# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/razor7877/ENSEIRB/KademliaTransfer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/razor7877/ENSEIRB/KademliaTransfer/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razor7877/ENSEIRB/KademliaTransfer/build/CMakeFiles /home/razor7877/ENSEIRB/KademliaTransfer/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razor7877/ENSEIRB/KademliaTransfer/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KademliaClient

# Build rule for target.
KademliaClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KademliaClient
.PHONY : KademliaClient

# fast build rule for target.
KademliaClient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/build
.PHONY : KademliaClient/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

lib/hash/hashmap.o: lib/hash/hashmap.c.o
.PHONY : lib/hash/hashmap.o

# target to build an object file
lib/hash/hashmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/lib/hash/hashmap.c.o
.PHONY : lib/hash/hashmap.c.o

lib/hash/hashmap.i: lib/hash/hashmap.c.i
.PHONY : lib/hash/hashmap.i

# target to preprocess a source file
lib/hash/hashmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/lib/hash/hashmap.c.i
.PHONY : lib/hash/hashmap.c.i

lib/hash/hashmap.s: lib/hash/hashmap.c.s
.PHONY : lib/hash/hashmap.s

# target to generate assembly for a file
lib/hash/hashmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/lib/hash/hashmap.c.s
.PHONY : lib/hash/hashmap.c.s

src/bucket.o: src/bucket.c.o
.PHONY : src/bucket.o

# target to build an object file
src/bucket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/bucket.c.o
.PHONY : src/bucket.c.o

src/bucket.i: src/bucket.c.i
.PHONY : src/bucket.i

# target to preprocess a source file
src/bucket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/bucket.c.i
.PHONY : src/bucket.c.i

src/bucket.s: src/bucket.c.s
.PHONY : src/bucket.s

# target to generate assembly for a file
src/bucket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/bucket.c.s
.PHONY : src/bucket.c.s

src/client.o: src/client.c.o
.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/client.c.s
.PHONY : src/client.c.s

src/command.o: src/command.c.o
.PHONY : src/command.o

# target to build an object file
src/command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/command.c.o
.PHONY : src/command.c.o

src/command.i: src/command.c.i
.PHONY : src/command.i

# target to preprocess a source file
src/command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/command.c.i
.PHONY : src/command.c.i

src/command.s: src/command.c.s
.PHONY : src/command.s

# target to generate assembly for a file
src/command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/command.c.s
.PHONY : src/command.c.s

src/http.o: src/http.c.o
.PHONY : src/http.o

# target to build an object file
src/http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/http.c.o
.PHONY : src/http.c.o

src/http.i: src/http.c.i
.PHONY : src/http.i

# target to preprocess a source file
src/http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/http.c.i
.PHONY : src/http.c.i

src/http.s: src/http.c.s
.PHONY : src/http.s

# target to generate assembly for a file
src/http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/http.c.s
.PHONY : src/http.c.s

src/list.o: src/list.c.o
.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i
.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s
.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/list.c.s
.PHONY : src/list.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/log.c.s
.PHONY : src/log.c.s

src/magnet.o: src/magnet.c.o
.PHONY : src/magnet.o

# target to build an object file
src/magnet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/magnet.c.o
.PHONY : src/magnet.c.o

src/magnet.i: src/magnet.c.i
.PHONY : src/magnet.i

# target to preprocess a source file
src/magnet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/magnet.c.i
.PHONY : src/magnet.c.i

src/magnet.s: src/magnet.c.s
.PHONY : src/magnet.s

# target to generate assembly for a file
src/magnet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/magnet.c.s
.PHONY : src/magnet.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/main.c.s
.PHONY : src/main.c.s

src/network.o: src/network.c.o
.PHONY : src/network.o

# target to build an object file
src/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/network.c.o
.PHONY : src/network.c.o

src/network.i: src/network.c.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/network.c.i
.PHONY : src/network.c.i

src/network.s: src/network.c.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/network.c.s
.PHONY : src/network.c.s

src/peer.o: src/peer.c.o
.PHONY : src/peer.o

# target to build an object file
src/peer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/peer.c.o
.PHONY : src/peer.c.o

src/peer.i: src/peer.c.i
.PHONY : src/peer.i

# target to preprocess a source file
src/peer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/peer.c.i
.PHONY : src/peer.c.i

src/peer.s: src/peer.c.s
.PHONY : src/peer.s

# target to generate assembly for a file
src/peer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/peer.c.s
.PHONY : src/peer.c.s

src/rpc.o: src/rpc.c.o
.PHONY : src/rpc.o

# target to build an object file
src/rpc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/rpc.c.o
.PHONY : src/rpc.c.o

src/rpc.i: src/rpc.c.i
.PHONY : src/rpc.i

# target to preprocess a source file
src/rpc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/rpc.c.i
.PHONY : src/rpc.c.i

src/rpc.s: src/rpc.c.s
.PHONY : src/rpc.s

# target to generate assembly for a file
src/rpc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/rpc.c.s
.PHONY : src/rpc.c.s

src/shared.o: src/shared.c.o
.PHONY : src/shared.o

# target to build an object file
src/shared.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/shared.c.o
.PHONY : src/shared.c.o

src/shared.i: src/shared.c.i
.PHONY : src/shared.i

# target to preprocess a source file
src/shared.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/shared.c.i
.PHONY : src/shared.c.i

src/shared.s: src/shared.c.s
.PHONY : src/shared.s

# target to generate assembly for a file
src/shared.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/shared.c.s
.PHONY : src/shared.c.s

src/storage.o: src/storage.c.o
.PHONY : src/storage.o

# target to build an object file
src/storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/storage.c.o
.PHONY : src/storage.c.o

src/storage.i: src/storage.c.i
.PHONY : src/storage.i

# target to preprocess a source file
src/storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/storage.c.i
.PHONY : src/storage.c.i

src/storage.s: src/storage.c.s
.PHONY : src/storage.s

# target to generate assembly for a file
src/storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KademliaClient.dir/build.make CMakeFiles/KademliaClient.dir/src/storage.c.s
.PHONY : src/storage.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... KademliaClient"
	@echo "... lib/hash/hashmap.o"
	@echo "... lib/hash/hashmap.i"
	@echo "... lib/hash/hashmap.s"
	@echo "... src/bucket.o"
	@echo "... src/bucket.i"
	@echo "... src/bucket.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/command.o"
	@echo "... src/command.i"
	@echo "... src/command.s"
	@echo "... src/http.o"
	@echo "... src/http.i"
	@echo "... src/http.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/magnet.o"
	@echo "... src/magnet.i"
	@echo "... src/magnet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/peer.o"
	@echo "... src/peer.i"
	@echo "... src/peer.s"
	@echo "... src/rpc.o"
	@echo "... src/rpc.i"
	@echo "... src/rpc.s"
	@echo "... src/shared.o"
	@echo "... src/shared.i"
	@echo "... src/shared.s"
	@echo "... src/storage.o"
	@echo "... src/storage.i"
	@echo "... src/storage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

